### ISSUE TITLE
Better show farmers and their products

### ISSUE THREAD

**Issue by enricodoro** [bl4ckj4c/polito-se2-21-P01-SPG#5]
In case there are a lot of farmers with a lot of products, it would be easier to have a collection of farmers and, by clicking on one of them, show the list of all their products.
For example:

+ farmer1
+ farmer2
+ farmer3
- farmer4
   + product1
   + product2
+ farmer5
...

**Comment by include-jacopo** [comment]
For the moment we have decided not to implement this function for choices of consistency with the rest of the site. Thank you.
