### ISSUE TITLE
Profile picture of the customers

### ISSUE THREAD

**Issue by MattiaRiola** [bl4ckj4c/polito-se2-21-P01-SPG#8]
The cards of the customers are very nice,
but it would be perfect with profile picture so the employee can recognise the customer easier. is it possible to add this feature?

Thank you in advice

**Comment by include-jacopo** [comment]
Thank you very much.  It is a really nice idea, but for the moment we do not have the possibility to reserve to the image the security they deserve and given that they concern personal data of the customer we prefer not to implement it at the moment.
